# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python auto_schema tests

on:
  pull_request:
    branches: [main]
    paths:
      - python/**
      - .github/workflows/python_ci.yml

defaults:
  run:
    working-directory: ./python/auto_schema

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgresql-version: [14.6, 15.4, "16rc1"]

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:${{ matrix.postgresql-version }}
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

      sqlite:
        image: nouchka/sqlite3
    steps:
    - uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
        cache: pipenv
        cache-dependency-path: python/Pipfile.lock

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip 
        pip install pipenv==2026.0.3

    - name: Install dependencies
      run: |
        pipenv install --deploy --dev

    - name: run test suite
      run: |
        pipenv run pytest -svv
      env:
        DB_CONNECTION_STRING: 'postgresql://postgres:postgres@localhost:5432'
